DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
  id         INTEGER,
  email      CHARACTER VARYING(255) NOT NULL UNIQUE,
  password   CHARACTER VARYING(255) NOT NULL,
  group_type CHARACTER VARYING(255) NOT NULL DEFAULT 'USER',
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

